import type { TrendFoodCandidate } from './types'

/**
 * MZ 음식 트렌드 후보 레지스트리.
 * seasonal pack 문항 작성 전 단계의 후보군을 관리합니다.
 *
 * 관리 규칙:
 * - evidenceLevel C 항목 등록 금지
 * - archived 항목은 삭제하지 말고 상태만 변경 (히스토리 보존)
 * - questionReady: true 항목만 seasonal pack 후보로 사용
 */
export const CANDIDATE_REGISTRY: TrendFoodCandidate[] = [
  {
    id: 'cnd_001',
    name: '우베 라떼',
    aliases: ['ube latte', '우베'],
    category: 'dessert',
    sourceType: ['sns', 'cafe_menu'],
    firstSeenAt: '2024-03-01',
    peakStartAt: '2024-07-01',
    trendStatus: 'rising',
    visualKeywords: ['보라색', '라떼', '카페 음료', '필리핀 식재료'],
    tags: ['디저트', '카페', '보라색', '수입 식재료'],
    evidenceLevel: 'B',
    sourceNotes: '필리핀산 우베(보라 고구마) 기반. 인스타 해시태그 급증.',
    questionReady: false,
  },
  {
    id: 'cnd_002',
    name: '두바이 초콜릿',
    aliases: ['두바이 초코', 'Dubai chocolate', '크런치 초콜릿'],
    category: 'dessert',
    sourceType: ['sns', 'convenience'],
    firstSeenAt: '2024-09-01',
    peakStartAt: '2024-10-01',
    peakEndAt: '2025-02-28',
    trendStatus: 'declining',
    visualKeywords: ['초콜릿 바', '피스타치오', '카다이프 면', '골드 포장'],
    tags: ['디저트', 'SNS', '편의점', '수입 식품'],
    evidenceLevel: 'A',
    sourceNotes: '중동 기원. 국내 편의점 3사 동시 출시. 오픈런 현상.',
    questionReady: true,
  },
  {
    id: 'cnd_003',
    name: '말차쫀득쿠키',
    aliases: ['말차 쿠키', '녹차 쫀득쿠키'],
    category: 'snack',
    sourceType: ['sns', 'homecook'],
    firstSeenAt: '2024-01-01',
    peakStartAt: '2024-04-01',
    trendStatus: 'active',
    visualKeywords: ['녹색 쿠키', '말차 파우더', '홈베이킹'],
    tags: ['간식', '홈베이킹', '말차', '쫀득'],
    evidenceLevel: 'B',
    questionReady: false,
  },
  {
    id: 'cnd_004',
    name: '요거트 아이스크림',
    aliases: ['요아이', '요거트 소프트아이스크림'],
    category: 'dessert',
    sourceType: ['cafe_menu', 'sns'],
    firstSeenAt: '2023-06-01',
    peakStartAt: '2023-09-01',
    peakEndAt: '2024-06-30',
    trendStatus: 'active',
    visualKeywords: ['소프트아이스크림', '요거트', '과일 토핑', '하얀 아이스크림'],
    tags: ['디저트', '아이스크림', '건강 디저트'],
    evidenceLevel: 'A',
    sourceNotes: '요아이 열풍. 전문점 프랜차이즈화.',
    questionReady: true,
  },
  {
    id: 'cnd_005',
    name: '버터떡',
    aliases: ['버터 가래떡', '버터구이떡'],
    category: 'snack',
    sourceType: ['sns', 'restaurant'],
    firstSeenAt: '2024-02-01',
    peakStartAt: '2024-06-01',
    trendStatus: 'rising',
    visualKeywords: ['구운 떡', '버터', '달달한 길거리 음식'],
    tags: ['간식', '길거리', '전통 식재료', '퓨전'],
    evidenceLevel: 'B',
    questionReady: false,
  },
  {
    id: 'cnd_006',
    name: '흑임자 라떼',
    aliases: ['흑임자 음료', '검은깨 라떼'],
    category: 'drink',
    sourceType: ['cafe_menu', 'sns'],
    firstSeenAt: '2023-01-01',
    peakStartAt: '2023-05-01',
    peakEndAt: '2024-03-31',
    trendStatus: 'active',
    visualKeywords: ['검은색 음료', '고소한 라떼', '카페 음료'],
    tags: ['음료', '카페', '건강 재료', '고소한 맛'],
    evidenceLevel: 'A',
    questionReady: true,
  },
  {
    id: 'cnd_007',
    name: '편의점 산도',
    aliases: ['샌드위치 도넛', '산도'],
    category: 'convenience',
    sourceType: ['convenience', 'sns'],
    firstSeenAt: '2024-01-01',
    peakStartAt: '2024-03-01',
    trendStatus: 'active',
    visualKeywords: ['편의점 베이커리', '샌드위치 형 도넛', '크림 필링'],
    tags: ['편의점', '베이커리', 'SNS 맛집'],
    evidenceLevel: 'A',
    sourceNotes: '편의점 3사 경쟁 출시. 줄서기 현상.',
    questionReady: true,
  },
  {
    id: 'cnd_008',
    name: '탕후루',
    aliases: ['설탕 코팅 과일', '탕후루 과일'],
    category: 'snack',
    sourceType: ['sns', 'restaurant'],
    firstSeenAt: '2022-10-01',
    peakStartAt: '2023-03-01',
    peakEndAt: '2023-12-31',
    trendStatus: 'declining',
    visualKeywords: ['설탕 코팅', '딸기', '포도', '길거리 꼬치'],
    tags: ['간식', '길거리', '중식', 'SNS'],
    evidenceLevel: 'A',
    sourceNotes: '2023년 대폭발 후 급격 하락. 전문 브랜드 폐업 속출.',
    questionReady: true,
  },
  {
    id: 'cnd_009',
    name: '크로플',
    aliases: ['크루아상 와플', 'croffle'],
    category: 'dessert',
    sourceType: ['cafe_menu', 'sns'],
    firstSeenAt: '2021-04-01',
    peakStartAt: '2021-08-01',
    peakEndAt: '2022-06-30',
    trendStatus: 'archived',
    visualKeywords: ['바삭한 페이스트리', '와플 모양', '크루아상'],
    tags: ['디저트', '카페', '퓨전 베이커리'],
    evidenceLevel: 'A',
    sourceNotes: '코로나 이후 카페 히트. 현재는 일반 메뉴화로 트렌드 소멸.',
    questionReady: true,
  },
  {
    id: 'cnd_010',
    name: '흑당 밀크티',
    aliases: ['흑당 버블티', '흑당 음료'],
    category: 'drink',
    sourceType: ['cafe_menu', 'sns'],
    firstSeenAt: '2019-06-01',
    peakStartAt: '2019-09-01',
    peakEndAt: '2020-06-30',
    trendStatus: 'archived',
    visualKeywords: ['흑당 시럽', '밀크티', '타이거 마블링'],
    tags: ['음료', '버블티', '대만 식문화'],
    evidenceLevel: 'A',
    sourceNotes: '대만 기원. 국내 전문점 우후죽순 후 포화.',
    questionReady: true,
  },
  {
    id: 'cnd_011',
    name: '그릭요거트 파르페',
    aliases: ['그릭요거트 볼', '그릭요거트 디저트'],
    category: 'wellness',
    sourceType: ['sns', 'cafe_menu'],
    firstSeenAt: '2023-09-01',
    peakStartAt: '2024-02-01',
    trendStatus: 'rising',
    visualKeywords: ['그릭요거트', '그래놀라', '과일', '건강 디저트'],
    tags: ['건강식', '브런치', '단백질', '저당'],
    evidenceLevel: 'B',
    questionReady: false,
  },
  {
    id: 'cnd_012',
    name: '과일 샌드위치',
    aliases: ['후루츠 산도', '과일 산도'],
    category: 'snack',
    sourceType: ['cafe_menu', 'convenience'],
    firstSeenAt: '2021-03-01',
    peakStartAt: '2021-06-01',
    peakEndAt: '2022-09-30',
    trendStatus: 'declining',
    visualKeywords: ['식빵', '생크림', '과일', '단면 샌드위치'],
    tags: ['간식', '일본 식문화', '카페', '편의점'],
    evidenceLevel: 'A',
    sourceNotes: '일본 후루츠 산도 영향. 편의점 상품화로 대중화 후 하락.',
    questionReady: true,
  },
]
